name: visf_flutterx
description: _
version: 1.1.1
homepage: _
publish_to: "none"

environment:
  sdk: ">=2.17.6 <4.0.0"
  flutter: ">=3.0.5"

dependencies:
  flutter:
    sdk: flutter
  visf_dartx:
    path: ../visf_dartx
  plugin_platform_interface: ^2.1.4
  device_info_plus: ^9.0.2
  package_info_plus: ^4.0.2
  permission_handler: ^10.4.2
  wakelock_plus: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
