version: 1.1.136+136
name: debug_app
description: _
publish_to: "none"

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  lib_ble:
    path: ../
  visf_flutterx:
    path: ../../visf_flutterx

  # flutter_hooks: ^0.20.3
  # hooks_riverpod: ^2.4.8
  # riverpod_annotation: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.4.6
  custom_lint: ^0.5.7
  riverpod_generator: ^2.3.8
  riverpod_lint: ^2.3.6

flutter:
  uses-material-design: true
