version: 1.1.136+136
name: debug_app
description: _
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  lib_ble:
    path: ../
  visf_flutterx:
    path: ../../visf_flutterx

  rxdart: ^0.27.7
  crypto: ^3.0.3
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.5
  fl_chart: ^0.63.0
  syncfusion_flutter_charts: ^22.1.34
  flutter_signal_processing: ^1.0.5
  bruno:
    git:
      url: https://github.com/ViShadowFiend/bruno.git
      ref: 3.x
  flutter_echarts: ^2.4.0
  path_provider: ^2.0.15
  path_provider_windows: ^2.1.6
  protobuf: ^2.1.0
  path: ^1.8.3
  file_picker: ^5.3.2
  visibility_detector: ^0.4.0+2
  flutter_easyloading: ^3.0.5
  flutter_keyboard_visibility: 5.4.1
  oktoast: ^3.3.1
  shared_preferences: ^2.2.0
  localstorage: ^4.0.1+2
  get: ^4.6.5
  get_storage: ^2.1.1
  date_format: ^2.0.7
  excel: 2.1.0

  flutter_hooks: ^0.18.6
  hooks_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  audio_waveforms: ^1.0.4
  just_audio: ^0.9.34
  ffmpeg_kit_flutter: 5.1.0-LTS

  reactive_forms: ^16.0.0
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  freezed: ^2.4.1
  custom_lint:
  riverpod_generator: ^2.2.3
  riverpod_lint: ^1.3.2

flutter:
  uses-material-design: true
